// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATT9h9ULBU9KH1QHe2tE2yPI8-KWVkM8U',
    appId: '1:749419715499:web:f6c95426bd5863de9490ee',
    messagingSenderId: '749419715499',
    projectId: 'caterpillarhackathon-13ede',
    authDomain: 'caterpillarhackathon-13ede.firebaseapp.com',
    storageBucket: 'caterpillarhackathon-13ede.appspot.com',
    measurementId: 'G-DPD0VJ77W9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA88ONBzTWi1N2bvrDtgPFIk6GjUhgTOr0',
    appId: '1:749419715499:android:388e2da98f8aa2109490ee',
    messagingSenderId: '749419715499',
    projectId: 'caterpillarhackathon-13ede',
    storageBucket: 'caterpillarhackathon-13ede.appspot.com',
  );
}
